# Generated by Django 5.0.4 on 2024-05-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='description',
            field=models.TextField(default='', help_text='Описание'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='university',
            field=models.CharField(blank=True, help_text='Alma-mater', max_length=160),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='scientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minerals', to='mainapp.scientist'),
        ),
    ]
