# Generated by Django 5.0.4 on 2024-05-08 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mineral_description_scientist_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='mainapp.scientist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='Описание книги', help_text='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_year',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), help_text='Год выпуска', null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='description',
            field=models.TextField(blank=True, default='A precious stone', help_text='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='discovery_year',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), help_text='Год открытия', null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='birth_year',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), help_text='Дата рождения', null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='country',
            field=models.CharField(blank=True, help_text='Страна', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='university',
            field=models.CharField(blank=True, help_text='Alma-mater', max_length=160, null=True),
        ),
    ]
